server:
    port: 8080
    servlet:
        context-path: /lotteshop
mybatis:
    mapper-locations: classpath:mappers/**/*.xml

spring:
    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize # 문서 > rest api > 인가코드
                        user-name-attribute: id #직접 쓰는 친구
                        token-uri: https://kauth.kakao.com/oauth/token # 문서 > rest api > 토큰받기
                        user-info-uri: https://kapi.kakao.com/v2/user/me # 문서 > rest api > 사용자 정보 가져오기
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent
                    naver:
                        authorization-uri : https://nid.naver.com/oauth2.0/authorize?prompt=login
                        user_name_attribute: response
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me

                registration:
                    kakao:
                        client-name: kakao #직접 쓰는 친구
                        authorization-grant-type: authorization_code #직접 쓰는 친구
                        redirect-uri: http://localhost:8080/sboard/login/oauth2/code/kakao #kakao > my application > redirect URI
                        client-id: f4f4a541f1f5bfb22fe74399fb26d44a #kakao > my application -> rest api key
                        client-secret: R6wHsQNPhmR40afxadEqnfb3kJrnidyH
                        client-authentication-method: client_secret_post
                        scope: profile_nickname, profile_image
                    google:
                        client-id: 357787742243-48nprd1h38bnptu1v4h4d70epuumfn23.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/sboard/login/oauth2/code/google
                        scope:
                            - email
                            - profile
                    naver:
                        client-name: naver
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        client-id: XAIYzlm6pgTUrsvvVz8P
                        client-secret: r_IphLfimA
                        redirect-uri: http://localhost:8080/sboard/login/oauth2/code/naver
                        scope: email, nickname, name

    application:
        name: lotteshop
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Password1!
        url: jdbc:mysql://43.200.184.246/farmstory_4
        username: abc1234
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    # 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: gahui446@gmail.com
        password: bwyj apiz cjng yltd
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
    thymeleaf:
        prefix: classpath:/templates

logging:
    file:
        name: logs/sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info


jwt:
    issuer: gahui446@gmail.com
    secret: eYgN3XAUp6AOJ089Il8TljMbX1W7KARC

# 파일 업로드 설정
file:
    upload:
        #개발용
        path: uploads/
        #배포용
        #path: /home/farmstory/uploads/

